import { SpiceItem } from './types';

export const INITIAL_GARAM_MASALA_SPICES: SpiceItem[] = [
  {
    id: 'spice-1',
    name: 'سفید زیرہ',
    englishName: 'White Cumin Seeds',
    weightGrams: 250,
    householdAmount: '1.5',
    householdUnit: 'کپ',
    householdMeasure: '1.5 کپ',
  },
  {
    id: 'spice-2',
    name: 'ثابت دھنیا',
    englishName: 'Whole Coriander Seeds',
    weightGrams: 250,
    householdAmount: '2',
    householdUnit: 'کپ',
    householdMeasure: '2 کپ',
  },
  {
    id: 'spice-3',
    name: 'کالی مرچ',
    englishName: 'Black Peppercorns',
    weightGrams: 250,
    householdAmount: '1.25',
    householdUnit: 'کپ',
    householdMeasure: '1.25 کپ',
  },
  {
    id: 'spice-4',
    name: 'شاہی زیرہ',
    englishName: 'Caraway / Shahi Jeera',
    weightGrams: 50,
    householdAmount: '8',
    householdUnit: 'چمچ',
    householdMeasure: '8 چمچ',
  },
  {
    id: 'spice-5',
    name: 'دار چینی',
    englishName: 'Cinnamon Sticks',
    weightGrams: 50,
    householdAmount: '12',
    householdUnit: 'عدد',
    householdMeasure: '12 عدد',
  },
  {
    id: 'spice-6',
    name: 'لونگ',
    englishName: 'Cloves',
    weightGrams: 50,
    householdAmount: '8',
    householdUnit: 'چمچ',
    householdMeasure: '8 چمچ',
  },
  {
    id: 'spice-7',
    name: 'سبز الائچی',
    englishName: 'Green Cardamom',
    weightGrams: 50,
    householdAmount: '200',
    householdUnit: 'عدد',
    householdMeasure: '200 عدد',
  },
  {
    id: 'spice-8',
    name: 'بڑی الائچی',
    englishName: 'Black Cardamom',
    weightGrams: 50,
    householdAmount: '35',
    householdUnit: 'عدد',
    householdMeasure: '35 عدد',
  },
  {
    id: 'spice-9',
    name: 'سونٹھ',
    englishName: 'Dry Ginger',
    weightGrams: 50,
    householdAmount: '4',
    householdUnit: 'عدد',
    householdMeasure: '4 عدد',
  },
  {
    id: 'spice-10',
    name: 'تیز پات',
    englishName: 'Bay Leaves',
    weightGrams: 25,
    householdAmount: '40',
    householdUnit: 'عدد',
    householdMeasure: '40 عدد',
  },
  {
    id: 'spice-11',
    name: 'جاوتری',
    englishName: 'Mace',
    weightGrams: 25,
    householdAmount: '20',
    householdUnit: 'عدد',
    householdMeasure: '20 عدد',
  },
  {
    id: 'spice-12',
    name: 'جائفل',
    englishName: 'Nutmeg',
    weightGrams: 25,
    householdAmount: '5',
    householdUnit: 'عدد',
    householdMeasure: '5 عدد',
  },
  {
    id: 'spice-13',
    name: 'بادیان کا پھول',
    englishName: 'Star Anise',
    weightGrams: 25,
    householdAmount: '15',
    householdUnit: 'عدد',
    householdMeasure: '15 عدد',
  },
  {
    id: 'spice-14',
    name: 'پیپلی (مگھاں)',
    englishName: 'Long Pepper (Pippali / Maghan)',
    weightGrams: 25,
    householdAmount: '25',
    householdUnit: 'عدد',
    householdMeasure: '25 عدد',
  },
];
