/**
 * @file defaultSpices.ts
 * @description معیاری اور روایتی مصالحہ جات کی ابتدائی ڈیفالٹ فہرست (14 اجزاء)
 * Baseline list of 14 traditional spice items used as the starting canvas.
 * Weights are initialized to 0 to encourage user-driven customization.
 */

import { SpiceItem } from './types';

export const INITIAL_GARAM_MASALA_SPICES: SpiceItem[] = [
  {
    id: 'spice-1',
    name: 'سفید زیرہ',
    englishName: 'White Cumin Seeds',
    weightGrams: 0,
    householdAmount: '',
    householdUnit: '',
    householdMeasure: '',
  },
  {
    id: 'spice-2',
    name: 'ثابت دھنیا',
    englishName: 'Whole Coriander Seeds',
    weightGrams: 0,
    householdAmount: '',
    householdUnit: '',
    householdMeasure: '',
  },
  {
    id: 'spice-3',
    name: 'کالی مرچ',
    englishName: 'Black Peppercorns',
    weightGrams: 0,
    householdAmount: '',
    householdUnit: '',
    householdMeasure: '',
  },
  {
    id: 'spice-4',
    name: 'شاہی زیرہ',
    englishName: 'Caraway / Shahi Jeera',
    weightGrams: 0,
    householdAmount: '',
    householdUnit: '',
    householdMeasure: '',
  },
  {
    id: 'spice-5',
    name: 'دار چینی',
    englishName: 'Cinnamon Sticks',
    weightGrams: 0,
    householdAmount: '',
    householdUnit: '',
    householdMeasure: '',
  },
  {
    id: 'spice-6',
    name: 'لونگ',
    englishName: 'Cloves',
    weightGrams: 0,
    householdAmount: '',
    householdUnit: '',
    householdMeasure: '',
  },
  {
    id: 'spice-7',
    name: 'سبز الائچی',
    englishName: 'Green Cardamom',
    weightGrams: 0,
    householdAmount: '',
    householdUnit: '',
    householdMeasure: '',
  },
  {
    id: 'spice-8',
    name: 'بڑی الائچی',
    englishName: 'Black Cardamom',
    weightGrams: 0,
    householdAmount: '',
    householdUnit: '',
    householdMeasure: '',
  },
  {
    id: 'spice-9',
    name: 'سونٹھ',
    englishName: 'Dry Ginger',
    weightGrams: 0,
    householdAmount: '',
    householdUnit: '',
    householdMeasure: '',
  },
  {
    id: 'spice-10',
    name: 'تیز پات',
    englishName: 'Bay Leaves',
    weightGrams: 0,
    householdAmount: '',
    householdUnit: '',
    householdMeasure: '',
  },
  {
    id: 'spice-11',
    name: 'جاوتری',
    englishName: 'Mace',
    weightGrams: 0,
    householdAmount: '',
    householdUnit: '',
    householdMeasure: '',
  },
  {
    id: 'spice-12',
    name: 'جائفل',
    englishName: 'Nutmeg',
    weightGrams: 0,
    householdAmount: '',
    householdUnit: '',
    householdMeasure: '',
  },
  {
    id: 'spice-13',
    name: 'بادیان کا پھول',
    englishName: 'Star Anise',
    weightGrams: 0,
    householdAmount: '',
    householdUnit: '',
    householdMeasure: '',
  },
  {
    id: 'spice-14',
    name: 'پیپلی (مگھاں)',
    englishName: 'Long Pepper (Pippali / Maghan)',
    weightGrams: 0,
    householdAmount: '',
    householdUnit: '',
    householdMeasure: '',
  },
];
